pwntester/ysoserial.net

- README.md
- ysoserial/Generators/WindowsIdentityGenerator.cs
```
$ ./ysoserial.exe -o base64 -g WindowsIdentity -f BinaryFormatter -c calc -t
AAEAAAD/////AQAAAAAAAAAEAQAAAClTeXN0ZW0uU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NJZGVudGl0eQEAAAAvU3lzdGVtLlNlY3VyaXR5LkNsYWltc0lkZW50aXR5LmJvb3RzdHJhcENvbnRleHQBBgIAAACsF0FBRUFBQUQvLy8vL0FRQUFBQUFBQUFBTUFnQUFBRWxUZVhOMFpXMHNJRlpsY25OcGIyNDlOQzR3TGpBdU1Dd2dRM1ZzZEhWeVpUMXVaWFYwY21Gc0xDQlFkV0pzYVdOTFpYbFViMnRsYmoxaU56ZGhOV00xTmpFNU16UmxNRGc1QlFFQUFBQ0VBVk41YzNSbGJTNURiMnhzWldOMGFXOXVjeTVIWlc1bGNtbGpMbE52Y25SbFpGTmxkR0F4VzF0VGVYTjBaVzB1VTNSeWFXNW5MQ0J0YzJOdmNteHBZaXdnVm1WeWMybHZiajAwTGpBdU1DNHdMQ0JEZFd4MGRYSmxQVzVsZFhSeVlXd3NJRkIxWW14cFkwdGxlVlJ2YTJWdVBXSTNOMkUxWXpVMk1Ua3pOR1V3T0RsZFhRUUFBQUFGUTI5MWJuUUlRMjl0Y0dGeVpYSUhWbVZ5YzJsdmJnVkpkR1Z0Y3dBREFBWUlqUUZUZVhOMFpXMHVRMjlzYkdWamRHbHZibk11UjJWdVpYSnBZeTVEYjIxd1lYSnBjMjl …
```
> Added BinaryFormatter support to the WindowsIdentity gadget

- ysoserial/Generators/ObjectDataProviderGenerator.cs
- ysoserial/packages.config
- ysoserial/ysoserial.csproj
@pwntester 
Adds functionality for YamlDotNet ObjectDataProvider gadget.  My proof of concept used to report this vulnerability to the maintainer was reading from a stream to bypass all of the expected type checking present.
I tested WindowsIdentity gadget as well, but the vulnerable version(s) of YamlDotNet instantiate the object with Activator.CreateInstance(Type), so the WindowsIdentity gadget is not a viable attack path here.
> add YamlDotNet payload generator for ObjectDataProvider

- ysoserial/Plugins/DotNetNukePlugin.cs
As per issue #18 In tests on a clean install of DotNetNuke 07.03.04 the payload mode run_command did not succeed. I have updated the payload mode to fix this issue.
> Fixed payload mode run_command

- ysoserial/Generators/ActivitySurrogateDisableTypeCheck.cs
- ysoserial/Generators/ActivitySurrogateSelectorFromFileGenerator.cs
- ysoserial/Generators/ActivitySurrogateSelectorGenerator.cs
- ysoserial/Generators/GenericGenerator.cs
- ysoserial/ysoserial.csproj
Reference: https://silentbreaksecurity.com/re-animating-activitysurrogateselector/
The current changes are very minimal in terms of "integration". I had some additional thoughts that might be good to discuss before merging:
- Currently both surrogate payloads will always be paired with the disable, but this would only be required if you were targeting newer framework versions. I don't suspect it would cause issues in earlier versions, but I hate making that assumption.
- I had considered some sort of flag argument to control code flow, but didn't want to alter the core `Generate(input, fmt, test)` format. If you are okay with this, maybe a flag for either version support or "mitigation bypasses". I'm happy to go any direction.
- Because we have to modify the AppSettings in ysoserial …
> Added type check disable to ActivitySurrogateSelector generators

- README.md
- ysoserial/Generators/TypeConfuseDelegateMonoGenerator.cs
- ysoserial/ysoserial.csproj
The `TypeConfuseDelegate` technique for Mono, but requires a tweak to work correctly. This PR adds a new generator that contains the tweak, allowing ysoserial.net to be used again Mono (and Unity) targets. Details on where the standard `TypeConfuseDelegate` fails in Mono is available here: https://gist.github.com/denandz/aa2b7bd145c95b430cfc0386a9e6ce40
> Added Mono compatible TypeConfuseDelegate generator

- ysoserial/ExploitClass.cs
Hi,
I simply added a fileless webshell example in ExploitClass.cs
In my past pentesting experience, the target always blocks all outgoing connection.
So I usually use this webshell to do more post-exploitation work.
Just hope everyone including me can directly reuse the example and save some time.
> Add a fileless webshell example in ExploitClass

- ysoserial/Generators/WindowsPrincipalGenerator.cs
- ysoserial/Helpers/SerializersHelper.cs
Hey guys,
This is a [WindowsPrinciple](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsprincipal.identity?view=dotnet-plat-ext-3.1) / WindowsClaimsPrincipal gadget chain for ysoserial that uses WindowsIdentity as an inner object. Nothing really new here, just a bridge to a bridge.
Also, I added the static serializer/deserializer for DataContractJsonSerializer since that was what I was using on my target. Enjoy and lmk if this needs edits.
> Added WindowsPrincipalGenerator

- README.md
- ysoserial/Generators/ActivitySurrogateSelectorFromFileGenerator.cs
- ysoserial/Generators/ActivitySurrogateSelectorGenerator.cs
- ysoserial/Generators/GenericGenerator.cs
- ysoserial/Generators/WindowsPrincipalGenerator.cs
- ysoserial/Helpers/SerializersHelper.cs
- ysoserial/Helpers/XMLMinifier.cs
- ysoserial/ysoserial.csproj
Fixed minifying bug in XML causing issues for WindowsPrincipal gadget (hpefully won't introduce another issue as XMLMinifier.cs has been updated!)
WindowsPrincipal gadget has been shortened by using another gadget
ActivitySurrogateSelector has been shortened more by fixing its BinaryFormatter/LosFormatter section (we do not need to use another gadget internally)
> bug fixing + shortenning

- README.md
- ysoserial/Generators/ObjectDataProviderGenerator.cs
- ysoserial/Helpers/SerializersHelper.cs
- ysoserial/Helpers/SharpSerializerHelpers/SharpSerializerHelperMethods.cs
- ysoserial/packages.config
- ysoserial/ysoserial.csproj
Added SharpSerializer formatter (and requisite helper methods) to the ObjectDataProvider gadget generator.
This is the only gadget that I could get to work successfully from the known list.
SharpSerializer gadget limitations:
- Must have a default (parameterless) constructor
- Uses Get/Set on properties to populate object so no serializing fields, etc.
- Properties must be public
- Setters (most of the time) need to be public
> SharpSerializer support (XML/Binary) for ObjectDataProvider gadget.

- ExploitClass/ExploitClass.csproj
- README.md
- ysoserial/Generators/ActivitySurrogateSelectorGenerator.cs
Credit section updated in Readme
ActivitySurrogateSelectorFromFile needed the E.dll file to work which was missing from the Release version (wrong config fixed) so ActivitySurrogateSelectorGenerator.cs has been updated to make ActivitySurrogateSelectorFromFile  works as usual even with a missing E.dll
> Readme update + ActivitySurrogateSelectorFromFile fixed

- ysoserial/Plugins/SharePointPlugin.cs
Just a quick, one-character typo fix.
> Typo fix: "poayloads" to "payloads"

- ysoserial/Plugins/SharePointPlugin.cs
```xaml
PS E:\code\ysoserial.net\ysoserial\bin\Debug> .\ysoserial.exe -p sharepoint --cve CVE-2019-0604 -c "cmd /c calc"
<ExpandedWrapperOfXamlReaderObjectDataProvider xmlns:a="http://www.w3.org/2001/XMLSchema-instance" xmlns:b="http://www.w3.org/2001/XMLSchema"><ExpandedElement/><ProjectedProperty0><MethodName>Parse</MethodName><MethodParameters><anyType a:type="b:string"><![CDATA[<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:a="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:b="clr-namespace:System;assembly=mscorlib" xmlns:c="clr-namespace:System.Diagnostics;assembly=system"><ObjectDataProvider a:Key="" ObjectType="{{a:Type c:Process}}" MethodName="Start"><ObjectDataProvider.MethodParameters><b:String>cmd</b:String><b:String>/c …
```
> fix bug of xaml for SharePoint CVE-2019-0604

- README.md
Main reason for change was that the README contained a reference to upload_file while it is named write_file
> Update DotNetNuke README to reflect actual output

- ExploitClass/ExploitClass.csproj
- TestConsoleApp/TestConsoleApp_YSONET.csproj
- ysoserial.sln
- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/ysoserial.csproj
Add IsolateApps support for generating viewstate payload.
Usage:
```bash
C:\Users\[REDACTED]\Desktop\Debug>ysoserial.exe -p ViewState -g TypeConfuseDelegate 
-c calc
--validationkey="220FFF8A54BB...,IsolateApps" --generator="C0C8685F" --isdebug 
--apppath="/test233"
Calculated new ValidationKey: 3B59C79954BB...
Provided __VIEWSTATEGENERATOR in uint: 3234359391
simulateTemplateSourceDirectory returns: /
simulateGetTypeName returns: _default_aspx
Calculated pageHashCode in uint (ignored): 460985631
/wEywBEAAQAAAP////8BAAAAAAAAAAwCAAAASVN5c3RlbSwgVmVyc...
```
> Add IsolateApps supports

- ysoserial/Generators/ObjRefGenerator.cs
- ysoserial/ysoserial.csproj
Deserializing the *ObjRef* gadget results in attempting to establish an outgoing connection to a specified .NET Remoting endpoint and sending a remoting method call to it. A rogue .NET Remoting server such as the [*RogueRemotingServer*](https://github.com/codewhitesec/RogueRemotingServer) can be used to serve `BinaryFormatter`/`SoapFormatter` payloads to connecting clients.
> Add ObjRef gadget

- ysoserial/Helpers/SerializersHelper.cs
- ysoserial/packages.config
- ysoserial/ysoserial.csproj
> code cleanup

- ysoserial/Helpers/CommandArgSplitter.cs
Fixing the single quote escaping issue in JSON messages. See https://github.com/pwntester/ysoserial.net/pull/135 for the bug report.
> Fixing the single quote escaping issue in JSON messages

- README.md
- ysoserial/Generators/ActivitySurrogateDisableTypeCheck.cs
- ysoserial/Generators/AxHostStateGenerator.cs
- ysoserial/Generators/ClaimsIdentityGenerator.cs
- ysoserial/Generators/ClaimsPrincipalGenerator.cs
- ysoserial/Generators/DataSetGenerator.cs
- ysoserial/Generators/DataSetTypeSpoofGenerator.cs
- ysoserial/Generators/GenericGenerator.cs
- ysoserial/Generators/IGenerator.cs
- ysoserial/Generators/RolePrincipalGenerator.cs
- ysoserial/Generators/SessionSecurityTokenGenerator.cs
- ysoserial/Generators/SessionViewStateHistoryItemGenerator.cs
- ysoserial/Generators/ToolboxItemContainerGenerator.cs
- ysoserial/Generators/TypeConfuseDelegateGenerator.cs
- ysoserial/Generators/WindowsClaimsIdentityGenerator.cs
- ysoserial/Generators/WindowsIdentityGenerator.cs
- ysoserial/Helpers/TestingArena/TestingArenaHome.cs
- ysoserial/Program.cs
The `--bridgedgadgetchains` option has been added which can be used to bridge different gadgets in one payload. Readme has been updated with the latest info
Minifier problem in ActivitySurrogateDisableTypeCheckGenerator has been addressed ActivitySurrogateDisableTypeCheckGenerator now can accept a variant for its underlying gadgets TestingArenaHome has slightly been updated with an example to read the DisableActivitySurrogateSelectorTypeCheck setting
> adding a feature & general updates

- ExploitClass/ExploitClass.cs
- README.md
- ysoserial/Generators/ActivitySurrogateSelectorFromFileGenerator.cs
- ysoserial/Generators/DataSetOldBehaviourFromFileGenerator.cs
- ysoserial/Generators/DataSetOldBehaviourGenerator.cs
- ysoserial/Generators/DataSetTypeSpoofGenerator.cs
- ysoserial/Generators/GenericPrincipalGenerator.cs
- ysoserial/Generators/IGenerator.cs
- ysoserial/Generators/ObjectDataProviderGenerator.cs
- ysoserial/Generators/TextFormattingRunPropertiesGenerator.cs
- ysoserial/Helpers/LocalCodeCompiler.cs
- ysoserial/Plugins/SharePointPlugin.cs
- ysoserial/Program.cs
- ysoserial/ysoserial.csproj
Three new gadgets have been added:
- DataSetOldBehaviourFromFile
- DataSetOldBehaviour
- GenericPrincipal Minor code improvements + fixing some typos
> Adding new gadgets & improvments

- ysoserial/App.config
- ysoserial/Generators/ObjectDataProviderGenerator.cs
- ysoserial/Helpers/MessagePackObjectDataProviderHelper.cs
- ysoserial/Helpers/SerializersHelper.cs
- ysoserial/packages.config
- ysoserial/ysoserial.csproj
MessagePack when in 'Typeless' mode (using the TypelessContractlessStandardResolver) will serialize type information along with the data. It uses property setters to initialize the objects it's deserializing. This allows use of the ObjectDataProvider gadget to achieve code execution.
The approach I've used is somewhat odd, but is due to some limitations of being able to control the properties that are serialized. There doesn't appear to be a mechanism to exclude properties (or even private fields) from serialization when using Typeless mode, so my approach is to create a surrogate object graph of the ObjectDataProvider in a dynamic assembly, then use reflection to modify MessagePack's internal type cache so that the surrogate objects are serialized with the real AssemblyQualifiedNames of …
> Added ObjectDataProvider gadget generation for MessagePack (Typeless)

- README.md
- ysoserial/Helpers/GadgetSurrogates/ObjectDataProviderSurrogates.cs
- ysoserial/Helpers/MessagePackObjectDataProviderHelper.cs
- ysoserial/Program.cs
- ysoserial/ysoserial.csproj
After running through some test code today I found that the approach of using a dynamic assembly to generate surrogate types isn't actually necessary. You can simply write the surrogate classes manually and then reference them, even if they're in the same assembly and it'll still work just fine.
I've made the changes as described above and also added MessagePackTypeless and MessagePackTypelessLz4 to the README. In addition I've added them both to the default Base64 behaviour and also included SharpSerializerBinary as that should also be in the same place.
I went back and forth on the pros and cons of continuing to use a dynamic assembly as I figured it reduces clutter in the codebase, since it's only used for generating this payload, however I figured that there may be other serializers …
> Reduced the necessary code to achieve gadget generation for MessagePackTypeless

- README.md
- ysoserial/Generators/XamlAssemblyLoadFromFileGenerator.cs
- ysoserial/ysoserial.csproj
Generates XAML that is similar to the one from [DataSetOldBehaviourFromFileGenerator](https://github.com/pwntester/ysoserial.net/blob/34485e2b2cc06c1ae5791b4ff8b42f073d24ca41/ysoserial/Generators/DataSetOldBehaviourFromFileGenerator.cs#L89), but with some improvements like gzip and base64 encoding.
> Added a generator for XAML that does Assembly.Load with compression

- README.md
- ysoserial/Generators/BaseActivationFactoryGenerator.cs
- ysoserial/Generators/GetterCompilerResultsGenerator.cs
- ysoserial/Generators/GetterSecurityExceptionGenerator.cs
- ysoserial/Generators/GetterSettingsPropertyValueGenerator.cs
- ysoserial/Generators/IGenerator.cs
- ysoserial/Generators/TextFormattingRunPropertiesGenerator.cs
- ysoserial/Generators/XamlImageInfo.cs
- ysoserial/Helpers/GadgetSurrogates/GetterSettingsPropertyValueSurrogates.cs
- ysoserial/Helpers/MessagePackGetterSettingsPropertyValueHelper.cs
- ysoserial/Plugins/GetterCallGadgetsPlugin.cs
- ysoserial/Plugins/NetNonRceGadgetsPlugin.cs
- ysoserial/Plugins/ThirdPartyGadgetsPlugin.cs
- ysoserial/ysoserial.csproj
Hi,
This PR implements a lot of stuff. This is an outcome of my Hexacon 2023 talk. White paper that describes all the implemented gadgets/plugin will be made public in a day or two - I will add a comment to this PR. Presentation video should be available soon.
Changes:
1) New gadgets in the main line 
Please note that some of the listed gadgets can be also implemented for some different formatters, but I didn't manage to test them against all of the possible serializers.
`GetterSecurityException` - RCE gadget for .NET Framework. This gadget chains Arbitrary Getter Call gadget and SecurityException serialization gadget (getter leads to BinaryFormatter). It has 4 variants. Every variant implements a different Arbitrary Getter Call gadget - PropertyGrid, ListBox, ComboBox, CheckedListBox. …
> Post hexacon

- README.md
Tell how to build ysoserial from source using command line. Inspired from the cicd.
> Document how to build from source

- ysoserial/Helpers/MachineKeyHelper.cs
- ysoserial/Plugins/MachineKeySessionSecurityTokenHandlerPlugin.cs
- ysoserial/packages.config
- ysoserial/ysoserial.csproj
The [Ysoserial.net](http://ysoserial.net/) tool includes an exploit plugin for the SessionSecurityTokenHandler security issue. However, due to the fact that SessionSecurityTokenHandler employs DPAPI for encryption and decryption, it is often difficult to exploit in most cases.
Nevertheless, Microsoft's documentation on SessionSecurityTokenHandler mentions that for web scenarios requiring a similar security mechanism, one can use the MachineKeySessionSecurityTokenHandler. This class inherits from SessionSecurityTokenHandler and shares similar characteristics. The key difference is that MachineKeySessionSecurityTokenHandler utilizes MachineKey configuration information for encryption and decryption operations. Therefore, as long as the MachineKey configuration information can be obtained …
> add MachineKeySessionSecurityTokenHandlerPlugin

- ysoserial/Helpers/LocalCodeCompiler.cs
This just implements changes suggested by James Williams at TrustedSec (don't know his github handle) in https://trustedsec.com/blog/spec-tac-ula-deserialization-deploying-specula-with-net 
Supporting pre-compiled DLL for XamlAssemblyLoadFromFile and its LocalCodeCompiler  helper can help streamline some cases where a payload has several reference assemblies to add.
> support pre-compiled DLL in LocalCodeCompiler helper
