pwntester/ysoserial.net

- ysoserial/Generators/ActivitySurrogateSelectorFromFileGenerator.cs
- ysoserial/Generators/ActivitySurrogateSelectorGenerator.cs
- ysoserial/Generators/TypeConfuseDelegateGenerator.cs
- ysoserial/ysoserial.csproj
Add support for:
* reading the exploit class from .cs file and compile it during runtime (ActivitySurrogateSelector)
* reading the command from file (TypeConfuseDelegate)
> Add support to read command/exploit class from file

- README.md
- ysoserial/Generators/TypeConfuseDelegateGenerator.cs
- ysoserial/Plugins/ApplicationTrustPlugin.cs
- ysoserial/Plugins/ClipboardPlugin.cs
- ysoserial/Plugins/ResxPlugin.cs
- ysoserial/Plugins/SessionSecurityTokenHandlerPlugin.cs
- ysoserial/Plugins/TransactionManagerReenlist.cs
- ysoserial/Plugins/altserializationPlugin.cs
New plugins were added and a generator file was updated to work better with the plugins.
The option output for the plugins need to be updated later to have correct indentation. Currently it is a little bit messy.
> My new plugins

- ysoserial/ExploitClass.cs
- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/Plugins/altserializationPlugin.cs
- ysoserial/ysoserial.csproj
Adding the ViewState plugin + adding System.Configuration reference.
More examples in the ExploitClass.cs to make it easier
Renaming a plugin to start with an uppercase letter
> View state plugin master

- ysoserial/ExploitClass.cs
- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/Plugins/altserializationPlugin.cs
- ysoserial/ysoserial_frmv2.csproj
Adding the ViewState plugin + adding System.Configuration reference.
More examples in the ExploitClass.cs to make it easier
Renaming a plugin to start with an uppercase letter
> ViewState plugin and some tweaks

- README.md
I have added the ViewState plugin
> V2 readme update

- ysoserial/Plugins/ViewStatePlugin.cs
> Fixing single slash problem

- ysoserial/Plugins/ViewStatePlugin.cs
Fixing the single slash problem
> Fixing the single slash problem

- ysoserial/Program.cs
When specifying complex command, it can be tedious to escape some special character (`;`, `|`, `&`, ..). By allowing stdin as a way to specify command, users can invoke Ysoserial this way:
```
cat my_long_cmd.txt | ysoserial.exe -o raw -g WindowsIdentity -f Json.Net -s
```
Bonus: I extract help display to a separate method for readability.
> Add the ability to specify commands in stdin

- ysoserial/Plugins/SharePointPlugin.cs
Update SharePointPlugin.cs Comments
> Update SharePointPlugin.cs Comments

- ysoserial/Plugins/ActivatorUrlPlugin.cs
- ysoserial/ysoserial.csproj
Add a plugin for attacking remote activated objects by their URL with a TypeConfuseDelegate gadget
> Add ActivatorUrlPlugin v1

- ysoserial/Plugins/ViewStatePlugin.cs
Fix ArgumentException thrown when validationAlg is 3DES in ViewState
> Fix ArgumentException thrown in ViewState plugin

- ysoserial/DevTest/SerializersHelper.cs
- ysoserial/Generators/WindowsClaimsIdentityGenerator.cs
- ysoserial/Program.cs
- ysoserial/packages.config
- ysoserial/ysoserial.csproj
+ added WindowsClaimsIdentityGenerator gadget
+ updated WindowsIdentityGenerator gadget
+ dev test lib added
+ default output set to raw when not provided
> 1 new gadget +gadget update

- README.md
- ysoserial/Generators/ClaimsIdentityGenerator.cs
- ysoserial/Generators/Generator.cs
- ysoserial/Generators/ResourceSetGenerator.cs
- ysoserial/Generators/RolePrincipalGenerator.cs
- ysoserial/Generators/WindowsClaimsIdentityGenerator.cs
- ysoserial/Generators/WindowsIdentityGenerator.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/AdvancedBinaryFormatterParser.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/binarycommonclasses.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/binaryformatter.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/binaryobjectinfo.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/binaryobjectreader.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/binaryobjectwriter.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/info.txt
- ysoserial/Program.cs
- ysoserial/ysoserial.csproj
ClaimsIdentity gadget has been added
ResourceSet has been hidden from normal menu as it is not a real gadget but is good to show how to work with raw bf payloads
some improvements in the local binaryformatter section
> Improvements + 1 new gadget

- ysoserial/Generators/ActivitySurrogateSelectorFromFileGenerator.cs
- ysoserial/Generators/ActivitySurrogateSelectorGenerator.cs
- ysoserial/Generators/ClaimsIdentityGenerator.cs
- ysoserial/Generators/GenericGenerator.cs
- ysoserial/Generators/TypeConfuseDelegateGenerator.cs
- ysoserial/Generators/TypeConfuseDelegateMonoGenerator.cs
- ysoserial/Helpers/FormatterType.cs
- ysoserial/Helpers/XMLMinifier.cs
Fixing the bug in ActivitySurrogateSelectorFromFile as it did not pass the input parameters to the payloadclass properly.
NetDataContract now rename the root element to make it shorter.
A few informatonal labels and comments have been edited
> bug fixing + improvements

- ysoserial/Generators/Generator.cs
- ysoserial/Generators/ResourceSetGenerator.cs
- ysoserial/Helpers/BinaryFormatterMinifier.cs
- ysoserial/Helpers/TestingArena/TestingArenaHome.cs
- ysoserial/Program.cs
improving BF minifier.
changing a gadget type from mask to dummy to make more sense.
> improving BF minifier

- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/packages.config
- ysoserial/ysoserial_frmv2.csproj
These are just address minor issues - but this project is not really inline with the main project so we probably can add more to it.
> old updates

- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/packages.config
- ysoserial/ysoserial_frmv2.csproj
> viewstate plugin update

- ysoserial/Generators/AxHostStateGenerator.cs
- ysoserial/Generators/ClaimsIdentityGenerator.cs
- ysoserial/Generators/GenericGenerator.cs
- ysoserial/Generators/IGenerator.cs
- ysoserial/Generators/RolePrincipalGenerator.cs
- ysoserial/Generators/SessionSecurityTokenGenerator.cs
- ysoserial/Generators/SessionViewStateHistoryItemGenerator.cs
- ysoserial/Generators/WindowsClaimsIdentityGenerator.cs
- ysoserial/Generators/WindowsIdentityGenerator.cs
- ysoserial/Plugins/ActivatorUrlPlugin.cs
- ysoserial/Plugins/AltserializationPlugin.cs
- ysoserial/Plugins/ApplicationTrustPlugin.cs
- ysoserial/Plugins/ClipboardPlugin.cs
- ysoserial/Plugins/DotNetNukePlugin.cs
- ysoserial/Plugins/IPlugin.cs
- ysoserial/Plugins/ResxPlugin.cs
- ysoserial/Plugins/SessionSecurityTokenHandlerPlugin.cs
- ysoserial/Plugins/SharePointPlugin.cs
- ysoserial/Plugins/TransactionManagerReenlist.cs
- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/Program.cs
- ysoserial/ysoserial.csproj
This is to increase its readibility
> Renaming interface classes

- ExploitClass/ExploitClass.csproj
- ExploitClass/GhostWebShell.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/SimpleBinaryFormatterParser.cs
- ysoserial/Helpers/SerializersHelper.cs
- ysoserial/Plugins/SharePointPlugin.cs
Calculate7BitEncodedInt bug has been fixed so it will not cause any error with a large amount of data. Closes #92 
A blog post will be published on the GhostWebShell topic to explain how it can be useful.
> bug fix + a few changes to existing modules

- README.md
- ysoserial/Generators/ToolboxItemContainerGenerator.cs
- ysoserial/ysoserial.csproj
Hi everybody,
as promised here is another bridge gadget for you I found several days ago as a by-product.
Not very exciting but at least allowed to bypass some filters for a custom app.
> Add ToolboxItemContainer Bridge Gadget

- README.md
- ysoserial/Generators/DataSetTypeSpoofGenerator.cs
- ysoserial/ysoserial.csproj
Hi,
I've just Add the DataSetTypeSpoof gadgetchain according to @mwulftange's blog
https://codewhitesec.blogspot.com/2022/06/bypassing-dotnet-serialization-binders.html
Can be helpful for some limitation cases bypass
> Add dataset type spoofing

- README.md
- ysoserial/Generators/ToolboxItemContainerGenerator.cs
- ysoserial/Generators/WindowsPrincipalGenerator.cs
- ysoserial/Plugins/DotNetNukePlugin.cs
- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/Program.cs
url encode feature (for the main app as well as the viewstate plugin)
save to file feature
> url encode feature + save to file

- ysoserial/Generators/TypeConfuseDelegateMonoGenerator.cs
This addresses the issue which was explained in #28 as the Mono gadget did not work
> Fixing the Mono gadget

- ysoserial/Generators/ActivitySurrogateDisableTypeCheck.cs
- ysoserial/Generators/AxHostStateGenerator.cs
- ysoserial/Generators/ClaimsIdentityGenerator.cs
- ysoserial/Generators/ClaimsPrincipalGenerator.cs
- ysoserial/Generators/GenericGenerator.cs
- ysoserial/Generators/ObjectDataProviderGenerator.cs
- ysoserial/Generators/PSObjectGenerator.cs
- ysoserial/Generators/ResourceSetGenerator.cs
- ysoserial/Generators/RolePrincipalGenerator.cs
- ysoserial/Generators/SessionSecurityTokenGenerator.cs
- ysoserial/Generators/SessionViewStateHistoryItemGenerator.cs
- ysoserial/Generators/TextFormattingRunPropertiesGenerator.cs
- ysoserial/Generators/ToolboxItemContainerGenerator.cs
- ysoserial/Generators/WindowsClaimsIdentityGenerator.cs
- ysoserial/Generators/WindowsIdentityGenerator.cs
- ysoserial/Generators/WindowsPrincipalGenerator.cs
- ysoserial/Helpers/JSONMinifier.cs
- ysoserial/Helpers/SerializersHelper.cs
- ysoserial/Helpers/TestingArena/TestingArenaHome.cs
- ysoserial/Helpers/XMLMinifier.cs
- ysoserial/Plugins/ApplicationTrustPlugin.cs
- ysoserial/Plugins/DotNetNukePlugin.cs
- ysoserial/Plugins/ResxPlugin.cs
- ysoserial/Plugins/SessionSecurityTokenHandlerPlugin.cs
- ysoserial/Plugins/SharePointPlugin.cs
- ysoserial/ysoserial.csproj
cosmetic changes for the serializer helper
adding spoofing example to TestingArenaHome
> serializer helper update + testing arena

- ysoserial/Program.cs
- Added "hex" output format for ASCII hex encoded output.
- Fixed broken stdin command input, and extended maximum inputted command length to 2048.
> Hex output stdin fixes

- ysoserial/Helpers/CommandArgSplitter.cs
Fixing bugs in cmd payloads' JavaScript escaping, and making the code more readable.
> Fixing bugs in cmd payloads' javascript escaping

- ExploitClass/ExploitClass.csproj
- README.md
> Readme update, code content update

- ysoserial/Plugins/ViewStatePlugin.cs
Just as is. Seems it was not available while generating viewstate
> added --stdin feature to ViewStatePlugin.cs

- ysoserial/Helpers/MachineKeyHelper.cs
- ysoserial/Plugins/MachineKeySessionSecurityTokenHandlerPlugin.cs
- ysoserial/packages.config
- ysoserial/ysoserial.csproj
SHA1 -> HMACSHA1 for MachineKeySessionSecurityTokenHandlerPlugin
> Update and small bug fix in MachineKeySessionSecurityTokenHandlerPlugin

- README.md
- ysoserial/Generators/ActivitySurrogateSelectorFromFileGenerator.cs
- ysoserial/Generators/BaseActivationFactoryGenerator.cs
- ysoserial/Generators/DataSetOldBehaviourFromFileGenerator.cs
- ysoserial/Generators/DataSetOldBehaviourGenerator.cs
- ysoserial/Generators/DataSetTypeSpoofGenerator.cs
- ysoserial/Generators/GetterCompilerResultsGenerator.cs
- ysoserial/Generators/GetterSecurityExceptionGenerator.cs
- ysoserial/Generators/GetterSettingsPropertyValueGenerator.cs
- ysoserial/Generators/IGenerator.cs
- ysoserial/Generators/ObjRefGenerator.cs
- ysoserial/Generators/ObjectDataProviderGenerator.cs
- ysoserial/Generators/RolePrincipalGenerator.cs
- ysoserial/Generators/SessionSecurityTokenGenerator.cs
- ysoserial/Generators/SessionViewStateHistoryItemGenerator.cs
- ysoserial/Generators/TextFormattingRunPropertiesGenerator.cs
- ysoserial/Generators/WindowsClaimsIdentityGenerator.cs
- ysoserial/Generators/WindowsIdentityGenerator.cs
- ysoserial/Generators/WindowsPrincipalGenerator.cs
- ysoserial/Generators/XamlAssemblyLoadFromFileGenerator.cs
- ysoserial/Generators/XamlImageInfo.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/AdvancedBinaryFormatterParser.cs
- ysoserial/Plugins/ClipboardPlugin.cs
- ysoserial/Plugins/GetterCallGadgetsPlugin.cs
- ysoserial/Plugins/NetNonRceGadgetsPlugin.cs
- ysoserial/Plugins/ThirdPartyGadgetsPlugin.cs
- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/Program.cs
> updating readme and typos

- README.md
- ysoserial/Generators/DataSetTypeSpoofGenerator.cs
- ysoserial/Helpers/ModifiedVulnerableBinaryFormatters/binarycommonclasses.cs
- ysoserial/Helpers/XmlHelper.cs
- ysoserial/Plugins/ViewStatePlugin.cs
- ysoserial/Program.cs
ViewState plugin has been updated to support more options. This update also includes fixes for issues reported via #122 and #166 - Thanks to @hexcat for the help
The wording has changed to address #155 as the output default depends on the formatter 
A minifier bug in NetDataContractor has been addressed (#158) 
The assembly name in DataSetTypeSpoof gadget has been updated to reflect its original blog post research
> Bug fixes & improvement
